### ISSUE TITLE
B3: Program must show if code was moved, as distinct from code that was changed or added.

### ISSUE THREAD

**Issue by jmtoniolo** [WSU-4110/PyMerge#21]
| B3: Program must show if code was moved, as distinct from code that was changed or added. |
|---|
|**Goal**: Show that code was moved and not added so users do not merge the same two code blocks twice by accident.
**Stakeholders:** Software Engineers|
| **Description:** If a code block is moved to another location, both locations in each version will be shown as added, and the user may merge both into the final synchronized version. If we check for and highlight code that we believe to have been moved, the user can make a more informed decision. |
| **Origin:** Team |
| **Version:** 1.0  |
|**Date:** 09/21/2019|
|  **Priority:** 3 |

**Comment by saularraffi-fo6197** [comment]
Saular will complete
