### ISSUE TITLE
Icons in button widget not showing up.

### ISSUE THREAD

**Issue by jmtoniolo** [WSU-4110/PyMerge#34]
In controlButtons.py you will see the buttons defined on line 23-35. The nextDbut and prevDBut icons are loaded similarly to the mergeL/R buttons but the icons do not show up in the buttons.

**Comment by malcolmraine** [comment]
Fixed. Icons now use paths defined in gui_config.py. Certain function names and instance names were changed to provide more description and adherence to PEP8.
