### ISSUE TITLE
Extension comparison between files won't allow users to compare files with changed extensions.

### ISSUE THREAD

**Issue by malcolmraine** [WSU-4110/PyMerge#35]
In algorithm.py:
        if f1_ext != f2_ext:
            print("[-] Incompatible file types", f1_ext, "and", f2_ext)
            return pmEnums.RESULT.FILEMISMAT

Files with **.dat**, **.txt**, and **.log** extensions could all contain text data but this logic wouldn't allow the program to compare the files due to differences in the extensions. File extensions do not necessarily indicate file format.

**Comment by jmtoniolo** [comment]
Don’t sanitized file object in algorithm.py. algorithm.py will be provided 2 file objects as input that will already be sanitized. The output objects (oChangesetA/B or something) are also already instantiated, simply populate those objects with the data.

**Comment by malcolmraine** [comment]
Fixed by not using this portion of the function at all.
